<Oval>:
    get:0
    Image:
        source:'IMG-20220428-WA0050.jpg'
    
    MDBoxLayout:
        orientation:'vertical'
        pos_hint:{'center_y':.65}
        size_hint_y:None 
        height:'100dp'
        spacing:'10dp'
    
    MDBoxLayout:
        orientation:'vertical'
        pos_hint:{'center_y':.15}
        size_hint_y:None 
        height:'100dp'
        spacing:'10dp'
    
    